### PR TITLE
2018 update (including circe 0.9.2)

### LINKED ISSUE #42: cats-core version conflicts - upgrading circe-core to 0.9.2
We get a dependency conflict during json decoding probably because stripe-scala transitively links in an older version of cats-core:0.9.1 via circe-core:0.8.0. An update to circe-core:0.9.2 would eventually solve the issue because it links cats-core:1.0.1, the version we do require.

This happens if we call `Customers.get`
```
java.lang.NoClassDefFoundError: cats/functor/Invariant
	at io.circe.Decoder$.<init>(Decoder.scala:776)
	at io.circe.Decoder$.<clinit>(Decoder.scala)
	at org.mdedetrich.stripe.v1.Customers$.<init>(Customers.scala:42)
	at org.mdedetrich.stripe.v1.Customers$.<clinit>(Customers.scala)
	at org.acme.id.app.http.api.services.stripepayment.domain.PaymentController.getSubscriptions(PaymentController.scala:67)
```

Upgrading to circe-core:0.9.2 could solve the issue, not sure about any side effects, though.

### PR DESCRIPTION
**Pull request by leonardehrenfried**
This PR does the following:

- upgrade to sbt 1.1.1
- use sbt 1 syntax for sbt-release
- don't run integration tests on PRs (because of secret variables)
- upgrade to circe 0.9.2

Fixes #42.

~This is WIP as builds are failing due to a bintray outage: http://status.bintray.com/ :(~

### CODE REVIEW

**Comment by leonardehrenfried** [comment]
@mdedetrich Can you review, merge and release?

**Comment by leonardehrenfried** [comment]
@mdedetrich Can you please take a look at this?

**Comment by mdedetrich** [comment]
Released as 0.3.0

**Comment by leonardehrenfried** [comment]
Great, thanks Matthew.

**Comment by onmomo** [comment]
thank you guys!

**Pull request merged**
